platform :ios, '5.0'

pod 'MKStoreKit'
pod 'MKNetworkKit'
pod 'SVProgressHUD'
pod 'EGOTableViewPullRefresh'
pod 'RegexKitLite'
pod 'CocoaLumberjack'
pod 'RNTimer'
pod 'TBXML'
pod 'TBXML+NSDictionary'
pod 'ZipArchive', '~> 1.2.0'